#!/bin/bash

# Enable the proxy extension in notebook and lab
jupyter serverextension enable --py jupyter_server_proxy
jupyter labextension install @jupyterlab/server-proxy
jupyter lab build

# Install the Pluto proxy
pip install -e.

julia -e "import Pkg; Pkg.add(Pkg.PackageSpec(;name=\"Pluto\", rev=\"183ec96\"))"